import { MenuItem, Testimonial, GalleryItem, WhyChooseItem, BusinessHours } from './types';

export const MENU_CATEGORIES = [
  'All',
  'Fresh Bread',
  'Breakfast',
  'Gourmet Pies & Rolls',
  'Pastries',
  'Cakes & Desserts',
  'Healthy Options',
  'Coffee & Drinks',
];

export const MENU_ITEMS: MenuItem[] = [
  // --- Fresh Bread ---
  {
    id: 'bread-sourdough',
    name: 'Sourdough Bread',
    description: 'Our signature 36-hour slow-fermented classic sourdough with a perfect crackling crust and airy, soft interior.',
    price: 8.50,
    category: 'Fresh Bread',
    image: 'https://images.unsplash.com/photo-1549931319-a545dcf3bc73?auto=format&fit=crop&q=80&w=600',
    isBestSeller: true,
    tags: ['Artisan', 'Vegan'],
  },
  {
    id: 'bread-white',
    name: 'Classic White Loaf',
    description: 'Soft, buttery, traditional white bread perfect for sandwiches and toast. Baked fresh daily.',
    price: 6.50,
    category: 'Fresh Bread',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=600',
    tags: ['Freshly Baked'],
  },
  {
    id: 'bread-wholemeal',
    name: 'Stoneground Wholemeal',
    description: 'Hearty loaf baked with stoneground organic wholemeal flour, rich in natural fibers and nutty flavor.',
    price: 7.50,
    category: 'Fresh Bread',
    image: 'https://images.unsplash.com/photo-1589415478042-76dc38302218?auto=format&fit=crop&q=80&w=600',
    tags: ['Healthy', 'Vegan'],
  },
  {
    id: 'bread-multigrain',
    name: 'Seeded Multigrain',
    description: 'Nutritious blend of toasted sesame, sunflower, pumpkin, and flaxseeds folded into an artisan wheat base.',
    price: 8.00,
    category: 'Fresh Bread',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=600',
    tags: ['High Fiber', 'Vegan'],
  },
  {
    id: 'bread-glutenfree',
    name: 'Gluten-Free Artisan Loaf',
    description: 'A beautifully structured, dense, gluten-free bread containing flaxseeds and chia. Incredibly toast-friendly!',
    price: 9.50,
    category: 'Fresh Bread',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80&w=600',
    tags: ['Gluten-Free', 'Vegetarian'],
  },
  {
    id: 'bread-baguettes',
    name: 'French Baguettes',
    description: 'Authentic Parisian-style crisp baguette. Golden crust on the outside, light and chewy on the inside.',
    price: 4.50,
    category: 'Fresh Bread',
    image: 'https://images.unsplash.com/photo-1598143153003-72ef7e94c3ee?auto=format&fit=crop&q=80&w=600',
    tags: ['Vegan', 'Artisan'],
  },

  // --- Breakfast ---
  {
    id: 'breakfast-bacon-egg',
    name: 'Bacon & Egg Roll',
    description: 'Crisp double bacon, two fried free-range eggs, cheddar cheese, and house smoky BBQ sauce on a toasted milk bun.',
    price: 11.90,
    category: 'Breakfast',
    image: 'https://images.unsplash.com/photo-1550507992-eb63ffee0847?auto=format&fit=crop&q=80&w=600',
    tags: ['Savoury', 'Popular'],
  },
  {
    id: 'breakfast-avo-toast',
    name: 'Avocado Toast',
    description: 'Smashed Hass avocado on toasted sourdough, premium Danish feta, cherry tomatoes, and a squeeze of fresh lemon.',
    price: 14.50,
    category: 'Breakfast',
    image: 'https://images.unsplash.com/photo-1541532713592-79a0317b6b77?auto=format&fit=crop&q=80&w=600',
    tags: ['Vegetarian', 'Healthy'],
  },
  {
    id: 'breakfast-wrap',
    name: 'Breakfast Wrap',
    description: 'Scrambled free-range eggs, baby spinach, bacon, and hash brown with tomato relish in a warm grilled tortilla.',
    price: 12.90,
    category: 'Breakfast',
    image: 'https://images.unsplash.com/photo-1626700051175-6518c4793f4f?auto=format&fit=crop&q=80&w=600',
    tags: ['Satisfying'],
  },
  {
    id: 'breakfast-toasties',
    name: 'Toasted Sandwiches',
    description: 'Triple cheese blend, shaved premium leg ham, and juicy vine tomatoes pressed in fresh house white bread.',
    price: 9.50,
    category: 'Breakfast',
    image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&q=80&w=600',
    tags: ['Comfort Food'],
  },

  // --- Gourmet Pies & Rolls ---
  {
    id: 'pie-chunky-beef',
    name: 'Chunky Beef Pie',
    description: 'Slow-cooked lean beef chunks in a rich, savory gravy inside our famous buttery, flaky shortcrust puff pastry.',
    price: 8.90,
    category: 'Gourmet Pies & Rolls',
    image: 'https://images.unsplash.com/photo-1608039829572-78524f79c4c7?auto=format&fit=crop&q=80&w=600',
    isBestSeller: true,
    tags: ['Local Favorite', 'Hot'],
  },
  {
    id: 'pie-chicken',
    name: 'Creamy Chicken & Leek Pie',
    description: 'Tender pulled chicken breast cooked in a creamy tarragon and leek sauce, wrapped in crisp golden pastry.',
    price: 8.90,
    category: 'Gourmet Pies & Rolls',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80&w=600',
    tags: ['Creamy'],
  },
  {
    id: 'pie-sausage-roll',
    name: 'Artisan Sausage Roll',
    description: 'Premium minced pork and beef blended with fresh herbs, garlic, and onions, rolled in flaky puff pastry.',
    price: 6.90,
    category: 'Gourmet Pies & Rolls',
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?auto=format&fit=crop&q=80&w=600',
    isBestSeller: true,
    tags: ['Classic', 'Freshly Baked'],
  },
  {
    id: 'pie-spinach-feta',
    name: 'Spinach & Feta Roll',
    description: 'Fresh baby spinach and crumbled tangy Greek feta cheese mixed with herbs, baked in light puff pastry.',
    price: 7.20,
    category: 'Gourmet Pies & Rolls',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80&w=600',
    tags: ['Vegetarian'],
  },
  {
    id: 'pie-vegetarian',
    name: 'Gourmet Vegetarian Pie',
    description: 'Hearty mix of roasted sweet potato, pumpkin, eggplant, and red peppers in a rich tomato-herb reduction.',
    price: 8.20,
    category: 'Gourmet Pies & Rolls',
    image: 'https://images.unsplash.com/photo-1519869325930-281384150729?auto=format&fit=crop&q=80&w=600',
    tags: ['Vegetarian', 'Healthy'],
  },

  // --- Pastries ---
  {
    id: 'pastry-butter',
    name: 'Butter Croissant',
    description: 'Classic French style. Incredibly light, flaky, airy, and prepared with 100% premium French butter.',
    price: 4.80,
    category: 'Pastries',
    image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&q=80&w=600',
    isBestSeller: true,
    tags: ['Classic', 'Vegetarian'],
  },
  {
    id: 'pastry-almond',
    name: 'Double Baked Almond Croissant',
    description: 'Filled with sweet frangipane (almond cream), baked twice and topped with toasted sliced almonds.',
    price: 6.20,
    category: 'Pastries',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=600',
    tags: ['Sweet', 'Popular'],
  },
  {
    id: 'pastry-chocolate',
    name: 'Chocolate Croissant (Pain au Chocolat)',
    description: 'Flaky pastry dough wrapped around two bars of premium dark Belgian chocolate. Pure morning bliss.',
    price: 5.50,
    category: 'Pastries',
    image: 'https://images.unsplash.com/photo-1608198093002-ad4e005484ec?auto=format&fit=crop&q=80&w=600',
    tags: ['Sweet', 'Vegetarian'],
  },
  {
    id: 'pastry-danish',
    name: 'Seasonal Fruit Danish',
    description: 'Flaky pastry filled with creamy vanilla custard and topped with fresh glazed seasonal fruits.',
    price: 5.90,
    category: 'Pastries',
    image: 'https://images.unsplash.com/photo-1608198093002-ad4e005484ec?auto=format&fit=crop&q=80&w=600',
    tags: ['Sweet', 'Vegetarian'],
  },
  {
    id: 'pastry-cinnamon',
    name: 'Glazed Cinnamon Scrolls',
    description: 'Soft yeast dough rolled with organic brown sugar, heavy cinnamon spice, topped with a velvety cream cheese frosting.',
    price: 5.50,
    category: 'Pastries',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=600',
    tags: ['Sweet', 'Warm'],
  },

  // --- Cakes & Desserts ---
  {
    id: 'cake-chocolate',
    name: 'Chocolate Tower Cake',
    description: 'Rich, multi-layered decadent chocolate sponge cake layered with dark chocolate ganache and chocolate curls.',
    price: 7.90,
    category: 'Cakes & Desserts',
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&q=80&w=600',
    isBestSeller: true,
    tags: ['Indulgent', 'Vegetarian'],
  },
  {
    id: 'cake-banana',
    name: 'Artisan Banana Bread',
    description: 'Moist and cakey banana bread infused with cinnamon, nutmeg, and honey. Served toasted with butter.',
    price: 5.50,
    category: 'Cakes & Desserts',
    image: 'https://images.unsplash.com/photo-1607958996333-41aef7caefaa?auto=format&fit=crop&q=80&w=600',
    isBestSeller: true,
    tags: ['Warm', 'Vegetarian'],
  },
  {
    id: 'cake-cheesecake',
    name: 'Baked NY Cheesecake',
    description: 'Silky, dense baked cream cheese filling on a crumbly biscuit base, topped with fresh berry coulis.',
    price: 7.50,
    category: 'Cakes & Desserts',
    image: 'https://images.unsplash.com/photo-1524351199679-46cddf530c04?auto=format&fit=crop&q=80&w=600',
    tags: ['Sweet', 'Creamy'],
  },
  {
    id: 'cake-muffins',
    name: 'Mixed Berry Muffin',
    description: 'Soft, moist giant muffin packed full of sweet blueberries and raspberries with a crunchy sugar crumble.',
    price: 4.80,
    category: 'Cakes & Desserts',
    image: 'https://images.unsplash.com/photo-1607958996333-41aef7caefaa?auto=format&fit=crop&q=80&w=600',
    tags: ['Fresh', 'Vegetarian'],
  },
  {
    id: 'cake-brownies',
    name: 'Double Chocolate Fudge Brownie',
    description: 'Fudgy, dense chocolate brownie with pockets of melted milk chocolate chunks and a paper-thin shiny crust.',
    price: 4.90,
    category: 'Cakes & Desserts',
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&q=80&w=600',
    tags: ['Gluten-Free Available', 'Sweet'],
  },
  {
    id: 'cake-cookies',
    name: 'Giant Choc Chip Cookie',
    description: 'Soft-baked New York style cookie filled with rich chocolate pools and sprinkled with sea salt flakes.',
    price: 4.20,
    category: 'Cakes & Desserts',
    image: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?auto=format&fit=crop&q=80&w=600',
    tags: ['Kid Friendly', 'Vegetarian'],
  },

  // --- Healthy Options ---
  {
    id: 'healthy-poke',
    name: 'Bakehouse Poke Bowl',
    description: 'Sashimi salmon or marinated tofu, brown rice, fresh edamame, pickled ginger, seaweeds, shredded cucumber, sesame.',
    price: 16.90,
    category: 'Healthy Options',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&q=80&w=600',
    tags: ['Healthy', 'Gluten-Free'],
  },
  {
    id: 'healthy-salad',
    name: 'Superfood Quinoa Salad',
    description: 'Tri-color quinoa, baby spinach, roasted pumpkin, pine nuts, pomegranate seeds, and a zesty honey-mustard vinaigrette.',
    price: 13.90,
    category: 'Healthy Options',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&q=80&w=600',
    tags: ['Vegan', 'Gluten-Free', 'Healthy'],
  },
  {
    id: 'healthy-veg-meal',
    name: 'Roasted Veggie & Halloumi Feast',
    description: 'Grilled premium halloumi cheese with slow-roasted Mediterranean vegetables, fresh rocket, and hummus sauce.',
    price: 15.50,
    category: 'Healthy Options',
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&q=80&w=600',
    tags: ['Vegetarian', 'Satisfying'],
  },
  {
    id: 'healthy-vegan',
    name: 'Vegan Buddha Bowl',
    description: 'Warm spiced chickpeas, baked falafel, shredded purple cabbage, shredded carrots, avocado rose, creamy tahini dressing.',
    price: 14.90,
    category: 'Healthy Options',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&q=80&w=600',
    tags: ['Vegan', 'Gluten-Free'],
  },
  {
    id: 'healthy-gf',
    name: 'Gluten-Free Warm Chicken Salad',
    description: 'Tender grilled chicken strips, mixed greens, crumbled feta, sliced almonds, olives, and extra virgin olive oil drizzle.',
    price: 15.90,
    category: 'Healthy Options',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&q=80&w=600',
    tags: ['Gluten-Free', 'High Protein'],
  },

  // --- Coffee & Drinks ---
  {
    id: 'drink-espresso',
    name: 'Espresso',
    description: 'Single shot of our signature Single Origin organic arabica beans, roasted in Sydney, boasting rich crema.',
    price: 4.00,
    category: 'Coffee & Drinks',
    image: 'https://images.unsplash.com/photo-1510972527409-cef190317417?auto=format&fit=crop&q=80&w=600',
    tags: ['Specialty Coffee'],
  },
  {
    id: 'drink-cappuccino',
    name: 'Cappuccino',
    description: 'Bold espresso shot with equal parts steamed milk and silky froth, dusted with premium cocoa powder.',
    price: 4.50,
    category: 'Coffee & Drinks',
    image: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&q=80&w=600',
    isBestSeller: true,
    tags: ['Artisan Coffee'],
  },
  {
    id: 'drink-latte',
    name: 'Latte',
    description: 'Espresso combined with smooth steamed milk and a thin layer of microfoam. Elegant and classic.',
    price: 4.50,
    category: 'Coffee & Drinks',
    image: 'https://images.unsplash.com/photo-1570968915860-54d5c301fc9f?auto=format&fit=crop&q=80&w=600',
    tags: ['Smooth'],
  },
  {
    id: 'drink-flatwhite',
    name: 'Flat White',
    description: 'The true Australian favorite. A double espresso shot capped with velvety textured milk, no froth.',
    price: 4.50,
    category: 'Coffee & Drinks',
    image: 'https://images.unsplash.com/photo-1577968897966-3d4325b36b61?auto=format&fit=crop&q=80&w=600',
    isBestSeller: true,
    tags: ['Australian Heritage', 'Popular'],
  },
  {
    id: 'drink-mocha',
    name: 'Caffè Mocha',
    description: 'A rich fusion of our bold espresso, rich Belgian chocolate syrup, and silky hot steamed milk.',
    price: 5.00,
    category: 'Coffee & Drinks',
    image: 'https://images.unsplash.com/photo-1578314675249-a6910f80cc4e?auto=format&fit=crop&q=80&w=600',
    tags: ['Sweet', 'Warm'],
  },
  {
    id: 'drink-hot-choc',
    name: 'Hot Chocolate',
    description: 'Velvety melted Swiss dark chocolate whisked with warm milk, served with fresh giant marshmallows.',
    price: 4.80,
    category: 'Coffee & Drinks',
    image: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&q=80&w=600',
    tags: ['Cozy'],
  },
  {
    id: 'drink-tea',
    name: 'Specialty Tea',
    description: 'Premium whole-leaf organic tea blends. Choose from English Breakfast, Earl Grey, Chamomile, or Organic Sencha Green.',
    price: 4.50,
    category: 'Coffee & Drinks',
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&q=80&w=600',
    tags: ['Organic'],
  },
  {
    id: 'drink-iced',
    name: 'Iced Coffee',
    description: 'Double espresso poured over ice and cold milk, crowned with a scoop of vanilla bean ice cream and whipped cream.',
    price: 6.50,
    category: 'Coffee & Drinks',
    image: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&q=80&w=600',
    tags: ['Refreshing', 'Indulgent'],
  },
  {
    id: 'drink-juice',
    name: 'Freshly Squeezed Juice',
    description: 'Fresh organic fruit squeezed on order. Choose from: Orange Press; or Green Glow (Apple, Cucumber, Celery, Mint).',
    price: 7.00,
    category: 'Coffee & Drinks',
    image: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?auto=format&fit=crop&q=80&w=600',
    tags: ['100% Raw', 'Healthy'],
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: 'review-1',
    name: 'Sarah Mitchell',
    role: 'Annandale Local',
    rating: 5,
    comment: 'The best croissants in Annandale and excellent coffee! The butter laminate layers are incredibly crisp and airy. We come here every single Saturday morning.',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=150',
  },
  {
    id: 'review-2',
    name: 'James Harrison',
    role: 'Food Enthusiast',
    rating: 5,
    comment: 'Friendly staff, fresh pastries, and an amazing atmosphere. It feels like stepping into a cozy neighborhood sanctuary. Do not miss their cinnamon scrolls!',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=150',
  },
  {
    id: 'review-3',
    name: 'Emma Watson',
    role: 'Daily Regular',
    rating: 5,
    comment: 'The sourdough bread and chunky beef pie are absolutely outstanding. The pie crust is extremely flaky, and the beef filling is incredibly savory and rich. Best bakery in the Inner West!',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&q=80&w=150',
  },
];

export const WHY_CHOOSE_US: WhyChooseItem[] = [
  {
    id: 'why-fresh',
    title: 'Freshly Baked Daily',
    description: 'Our bakers start firing up the stone ovens at 3:00 AM every single night so that you enjoy bread and pastries warm from the oven.',
    iconName: 'Sparkles',
  },
  {
    id: 'why-artisan',
    title: 'Artisan Bread',
    description: 'We use premium stoneground flours, high hydration levels, and traditional 36-hour sourdough fermentation with no preservatives.',
    iconName: 'Cookie',
  },
  {
    id: 'why-coffee',
    title: 'Premium Coffee',
    description: 'Specialty organic beans, freshly roasted locally in Sydney, pulled to golden perfection by passionate award-winning baristas.',
    iconName: 'Coffee',
  },
  {
    id: 'why-service',
    title: 'Friendly Service',
    description: 'We pride ourselves on our warm Australian hospitality. We remember your order, your name, and your favorite table.',
    iconName: 'Heart',
  },
  {
    id: 'why-vegan',
    title: 'Vegan & Vegetarian Options',
    description: 'Enjoy delicious veggie pies, plant-based rolls, milk alternatives, and complete nutritious salad bowls crafted with care.',
    iconName: 'Leaf',
  },
  {
    id: 'why-gf',
    title: 'Gluten-Free Choices',
    description: 'Our designated gluten-free options are prepared with strict separation guidelines to ensure safety without sacrificing flavor.',
    iconName: 'ShieldCheck',
  },
  {
    id: 'why-loved',
    title: 'Locally Loved',
    description: 'Proudly serving the Annandale community, providing a welcoming social gathering hub for families, friends, and remote workers.',
    iconName: 'MapPin',
  },
  {
    id: 'why-price',
    title: 'Affordable Prices',
    description: 'We believe premium artisan baking should be accessible to all. True handcrafting value with honest and reasonable neighborhood pricing.',
    iconName: 'Coins',
  },
];

export const GALLERY_ITEMS: GalleryItem[] = [
  {
    id: 'gal-1',
    title: 'Artisan Sourdough',
    category: 'Bread',
    image: 'https://images.unsplash.com/photo-1549931319-a545dcf3bc73?auto=format&fit=crop&q=80&w=800',
    description: 'Golden-brown, slow-fermented classic sourdough loaf fresh from our stone deck ovens.',
  },
  {
    id: 'gal-2',
    title: 'Golden Croissants',
    category: 'Pastry',
    image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&q=80&w=800',
    description: 'Flaky pastry with buttery, honeycomb layers using imported organic butter.',
  },
  {
    id: 'gal-3',
    title: 'Specialty Cakes',
    category: 'Cakes',
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&q=80&w=800',
    description: 'Elegant custom cakes and celebration slices crafted by our head pastry chef.',
  },
  {
    id: 'gal-4',
    title: 'Artisan Beef Pie',
    category: 'Pies',
    image: 'https://images.unsplash.com/photo-1608039829572-78524f79c4c7?auto=format&fit=crop&q=80&w=800',
    description: 'Hearty hand-folded shortcrust pie filled with slow-braised chunky premium Australian beef.',
  },
  {
    id: 'gal-5',
    title: 'Barista Latte Art',
    category: 'Coffee',
    image: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&q=80&w=800',
    description: 'Specialty cappuccino and flat whites poured with silky microfoam.',
  },
  {
    id: 'gal-6',
    title: 'Gourmet Breakfast',
    category: 'Breakfast',
    image: 'https://images.unsplash.com/photo-1541532713592-79a0317b6b77?auto=format&fit=crop&q=80&w=800',
    description: 'Smash-hit avocado on toast with slow-poached free-range eggs and seeds.',
  },
  {
    id: 'gal-7',
    title: 'The Bread Display',
    category: 'Bakery',
    image: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&q=80&w=800',
    description: 'Our morning bakery shelf stocked with baguettes, loaves, and rye options.',
  },
  {
    id: 'gal-8',
    title: 'Cosy Café Vibe',
    category: 'Café',
    image: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&q=80&w=800',
    description: 'Lightwood counters, warm lighting, and a cozy dining room in the heart of Annandale.',
  },
  {
    id: 'gal-9',
    title: 'Happy Neighborhood',
    category: 'Community',
    image: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&q=80&w=800',
    description: 'Welcoming our locals, serving families, and brewing daily smiles.',
  },
];

export const BUSINESS_HOURS: BusinessHours[] = [
  { day: 'Monday', hours: '6:30 AM - 4:00 PM' },
  { day: 'Tuesday', hours: '6:30 AM - 4:00 PM' },
  { day: 'Wednesday', hours: '6:30 AM - 4:00 PM' },
  { day: 'Thursday', hours: '6:30 AM - 4:30 PM' },
  { day: 'Friday', hours: '6:30 AM - 4:30 PM' },
  { day: 'Saturday', hours: '7:00 AM - 4:00 PM' },
  { day: 'Sunday', hours: '7:30 AM - 3:00 PM' },
];
